
# RESOLUTION:

SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# PLAYER:
PLAYER_RADIUS = 20 # radius of the player's ship
LINE_WIDTH = 2 # width of the lines that draw the player's ship

## PLAYER MOVING AROUND:

PLAYER_TURN_SPEED = 300 # turning speed

PLAYER_SPEED = 200 # moving speed

## ASTEROID:

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS


# SHOOT SPEED
PLAYER_SHOOT_SPEED = 500

# FIRE RATE
PLAYER_SHOOT_COOLDOWN_SECONDS = .3 # in seconds so 300ms

# BULLETS
SHOT_RADIUS = 5
